const state = { projection: null, economy: null, academy: null, cycles: [], runs: [], view: 'overview', filter: 'ALL' };
const views = { overview: ['WORLD', 'Overview'], agents: ['WORLD', 'Agents'], missions: ['WORLD', 'Missions'], world: ['WORLD', 'World'], economy: ['CIVILIZATION', 'Economy'], institutions: ['CIVILIZATION', 'Institutions'], academy: ['CIVILIZATION', 'Academy'], entertainment: ['CIVILIZATION', 'Entertainment'], governance: ['TRUST LAYER', 'Governance'], operations: ['TRUST LAYER', 'Operations'], evidence: ['TRUST LAYER', 'Evidence'] };
const $ = selector => document.querySelector(selector);
const esc = value => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;');
const short = value => value ? String(value).slice(0, 8) : '—';
const stamp = value => value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const clock = value => value ? new Date(value).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—';

async function api(url, options = {}) {
  const response = await fetch(url, { cache: 'no-store', ...options });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error ?? `${response.status} ${response.statusText}`);
  return data;
}
function agents() { return (state.projection?.agent_records ?? []).map(agent => ({ ...agent, id: agent.system_id, enabled: agent.presence !== 'OFFLINE', purpose: agent.role, capabilities: agent.granted_authority ?? [] })); }
function runs() { return state.runs ?? []; }
function badge(value = 'UNKNOWN') { const good = ['ONLINE', 'COMPLETED', 'VERIFIED', 'PASS', 'ACTIVE'].includes(value); return `<span class="badge ${good ? 'good' : 'muted'}"><span class="status-dot ${good ? 'live' : ''}"></span>${esc(value)}</span>`; }
function head(kicker, title, action = '') { return `<div class="section-heading"><div><span class="eyebrow">${kicker}</span><h2>${title}</h2></div>${action}</div>`; }
function empty(title, copy) { return `<div class="empty-state"><span class="empty-glyph">◌</span><strong>${title}</strong><p>${copy}</p></div>`; }
function metric(label, value, tone = '') { return `<div class="metric-card ${tone}"><span class="metric-label">${label}</span><strong>${esc(value)}</strong><span class="metric-rule"></span></div>`; }
function authority(agent) { return agent.id === 'SINK-PRIME' ? 'STEWARD' : agent.id === 'SINK-05' ? 'EVIDENCE' : agent.id === 'SINK-03' ? 'AUDIT' : agent.id === 'SINK-02' ? 'ENGINEERING' : agent.risk_class || 'BOUNDED'; }
function activity() { const persisted = runs().flatMap(run => (run.events ?? []).map(event => ({ ...event, run }))); const projected = (state.projection?.operations ?? []).map(operation => ({ agent_id: operation.agents?.[0] || 'SYSTEM', summary: operation.title, timestamp: operation.occurred_at, run: { run_id: operation.operation_id } })); return [...persisted, ...projected].sort((a, b) => String(b.timestamp).localeCompare(String(a.timestamp))).slice(0, 8); }

function overview() {
  const items = activity();
  const population = state.projection?.settlement?.population ?? '—';
  const generation = state.projection?.settlement?.generation ?? '—';
  const institutions = state.projection?.institutions?.length ?? '—';
  return `<div class="page-view"><section class="world-hero"><div class="hero-copy"><span class="eyebrow accent">LAKE YANGE / WORLD 01</span><h1>A living civilization,<br><em>carefully becoming.</em></h1><p>Bounded intelligence, persisted state, and evidence you can follow all the way home.</p><div class="hero-status">${badge('ONLINE')}<span>LOCAL PROJECTION</span><span class="mono">${stamp(new Date())}</span></div></div><div class="hero-signal"><div class="signal-ring ring-one"></div><div class="signal-ring ring-two"></div><div class="signal-core">◉<span>YANGE</span></div><i class="signal-point point-one"></i><i class="signal-point point-two"></i></div></section><section class="metric-grid">${metric('POPULATION', population, 'gold')}${metric('GENERATION', generation)}${metric('AGENTS', agents().length)}${metric('INSTITUTIONS', institutions)}</section><div class="content-grid"><section class="panel activity-panel">${head('WHAT IS HAPPENING NOW', 'Live activity', `<span class="panel-meta">${items.length} EVENTS</span>`)}${items.length ? `<div class="activity-list">${items.map(item => `<button class="activity-item" data-run-id="${esc(item.run.run_id)}"><span class="activity-marker"></span><span class="activity-main"><strong>${esc(item.agent_id || 'SYSTEM')}</strong><span>${esc(item.summary || item.type || 'State transition')}</span></span><span class="activity-time">${clock(item.timestamp)}</span></button>`).join('')}</div>` : empty('No activity recorded', 'Persisted run events will appear here when the world acts.')}</section><section class="panel pulse-panel">${head('WORLD PULSE', 'The trust layer')}<div class="pulse-stat"><div class="pulse-icon">✓</div><div><strong>Evidence-bound runtime</strong><span>Every visible action resolves to persisted state.</span></div></div><div class="pulse-stat"><div class="pulse-icon gold">◈</div><div><strong>${agents().length || 'No'} bounded agents registered</strong><span>Authority remains explicit at every boundary.</span></div></div><button class="text-button" data-navigate="governance">Inspect authority <span>→</span></button></section></div><section class="panel launch-panel">${head('ENTER THE WORLD', 'Choose a starting point')}<div class="launch-grid"><button class="launch-card" data-navigate="agents"><span class="launch-icon">◈</span><strong>Meet the agents</strong><small>Roles, boundaries, and real work.</small><span class="launch-arrow">↗</span></button><button class="launch-card" data-navigate="missions"><span class="launch-icon gold">✦</span><strong>Follow missions</strong><small>Trace work through its receipts.</small><span class="launch-arrow">↗</span></button><button class="launch-card" data-navigate="evidence"><span class="launch-icon">✓</span><strong>Open the audit trail</strong><small>See why the world can claim what it claims.</small><span class="launch-arrow">↗</span></button></div></section></div>`;
}
function agentsPage() { return `<div class="page-view">${head('WORLD / CAST', 'Agent command center', '<span class="panel-meta">REAL REGISTRY · READ ONLY</span>')}<div class="agent-grid">${agents().map(agent => `<button class="agent-card" data-agent-id="${esc(agent.id)}"><div class="agent-top"><span class="agent-sigil">${agent.id === 'SINK-PRIME' ? '◉' : '◈'}</span>${badge(agent.enabled ? 'ONLINE' : 'DISABLED')}</div><div class="agent-name">${esc(agent.name || agent.id)}</div><div class="agent-id mono">${esc(agent.id)}</div><p>${esc(agent.purpose || 'Bounded runtime agent')}</p><div class="agent-footer"><span><small>AUTHORITY</small><strong>${authority(agent)}</strong></span><span><small>CAPABILITIES</small><strong>${agent.capabilities?.length ?? 0}</strong></span></div></button>`).join('')}</div>${agents().length ? '' : empty('No agents registered', 'The runtime registry is currently empty.')}</div>`; }
function missionsPage() { const list = runs().filter(run => state.filter === 'ALL' || run.status === state.filter); return `<div class="page-view">${head('WORLD / INTENT', 'Mission ledger', `<div class="filter-tabs">${['ALL', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED'].map(filter => `<button class="filter-tab ${state.filter === filter ? 'active' : ''}" data-filter="${filter}">${filter}</button>`).join('')}</div>`)}${list.length ? `<div class="mission-list">${list.map(run => `<button class="mission-card" data-run-id="${esc(run.run_id)}"><div class="mission-card-main"><span class="mission-symbol">✦</span><div><span class="eyebrow">${esc(run.adapter || 'LOCAL ADAPTER')}</span><h3>${esc(run.objective || 'Untitled mission')}</h3><span class="mono">RUN ${short(run.run_id)} · ${stamp(run.created_at)}</span></div></div><div class="mission-card-side">${badge(run.status)}<span class="mission-arrow">↗</span></div></button>`).join('')}</div>` : empty('No missions in this state', 'The persisted run ledger has no matching missions.')}</div>`; }
function evidencePage() { const items = activity(); return `<div class="page-view">${head('TRUST LAYER / RED SINK', 'Evidence & audit', '<span class="panel-meta">PERSISTED RECEIPTS</span>')}<div class="evidence-banner"><div class="evidence-seal">✓</div><div><span class="eyebrow accent">NO ARTIFACT / NO CLAIM</span><h3>Trust is a visible system.</h3><p>Lake Yange exposes the events and receipts behind its projections.</p></div></div><section class="panel timeline-panel"><div class="timeline">${items.length ? items.map((item, index) => `<div class="timeline-item"><span class="timeline-line"></span><span class="timeline-dot">${index ? '○' : '●'}</span><div><span class="eyebrow">${clock(item.timestamp)} · ${esc(item.agent_id || 'SYSTEM')}</span><strong>${esc(item.summary || item.type || 'Recorded event')}</strong><p>Persisted in run <button class="inline-link" data-run-id="${esc(item.run.run_id)}">${short(item.run.run_id)}</button></p></div></div>`).join('') : empty('No audit events yet', 'Evidence will appear once a persisted run is available.')}</div></section></div>`; }
function governancePage() { const rows = [['Prime', 'SINK-PRIME', 'Steward / planning intelligence', 'STEWARD'], ['Vera', 'SINK-05', 'Evidence gathering and evaluation', 'EVIDENCE ONLY'], ['Forge', 'SINK-02', 'Bounded engineering execution', 'REQUIRES APPROVAL'], ['Red Sink', 'RED-SINK', 'Independent audit and rejection', 'AUDIT']]; return `<div class="page-view">${head('TRUST LAYER / AUTHORITY', 'Governance', '<span class="panel-meta">BOUNDARIES ARE EXPLICIT</span>')}<div class="governance-intro"><span class="eyebrow accent">AUTHORITY MAP</span><h3>Power is not implied by proximity.</h3><p>Planning, evidence, execution, and audit remain separate.</p></div><div class="authority-list">${rows.map(row => `<div class="authority-row"><span class="authority-symbol">${row[3] === 'STEWARD' ? '◉' : row[3] === 'AUDIT' ? '✓' : '○'}</span><div><strong>${row[0]}</strong><span class="mono">${row[1]}</span></div><p>${row[2]}</p><span class="authority-state">${row[3]}</span></div>`).join('')}</div></div>`; }
function operationsPage() { return `<div class="page-view">${head('TRUST LAYER / SYSTEM', 'Operations', '<span class="panel-meta">OPERATOR VIEW</span>')}<div class="ops-grid"><div class="panel ops-health"><span class="eyebrow">RUNTIME HEALTH</span><div class="health-readout"><span class="status-dot live"></span><strong>LOCAL RUNTIME ONLINE</strong></div><p>Persisted state is the authority for this console.</p><div class="health-line"><span>Registry</span><b>VALID</b></div><div class="health-line"><span>Receipts</span><b>${runs().length} RUNS</b></div></div><div class="panel ops-ledger"><span class="eyebrow">RUN QUEUE</span>${runs().slice(0, 6).map(run => `<button class="ops-run" data-run-id="${esc(run.run_id)}"><span class="status-dot ${run.status === 'COMPLETED' ? 'live' : ''}"></span><span>${esc(run.objective || 'Untitled run')}</span><b>${esc(run.status)}</b></button>`).join('') || empty('Queue is quiet', 'No persisted runs are available.')}</div></div></div>`; }
function institutionsPage() { return `<div class="page-view">${head('CIVILIZATION / STRUCTURE', 'Institutions', '<span class="panel-meta">WORLD PROJECTION</span>')}<div class="institution-grid">${(state.projection?.institutions || []).map(item => `<article class="panel institution-card"><span class="eyebrow">${esc(item.kind)}</span><h3>${esc(item.name)}</h3><p>${esc(item.purpose)}</p><div class="health-line"><span>STATUS</span><b>${esc(item.status)}</b></div><div class="health-line"><span>OCCUPANTS</span><b>${esc(item.occupants)}</b></div></article>`).join('') || empty('No institutions founded', 'The world projection contains no institution records.')}</div></div>`; }
function academyPage() { const academy = state.academy || {}; return `<div class="page-view">${head('CIVILIZATION / LEARNING', 'Academy', '<span class="panel-meta">PERSISTED ACADEMY STATE</span>')}<div class="metric-grid">${metric('STUDENTS', academy.students?.length ?? 0, 'gold')}${metric('ASSIGNMENTS', academy.assignments?.length ?? 0)}${metric('SUBMISSIONS', academy.submissions?.length ?? 0)}${metric('GRADES', academy.grades?.length ?? 0)}</div><section class="panel activity-panel"><span class="eyebrow">ACADEMY STATUS</span><h3>${academy.last_cycle_at ? `Last cycle ${stamp(academy.last_cycle_at)}` : 'No academy cycle recorded'}</h3><p class="muted-copy">Learning state is persisted by the Academy runtime. No completion is inferred from a single result.</p></section></div>`; }
function economyPage() { const economy = state.economy || {}; const money = value => `${economy.currency || 'AUD'} ${Number(value || 0).toFixed(2)}`; return `<div class="page-view">${head('CIVILIZATION / VALUE', 'Economy', '<span class="panel-meta">PERSISTED REVENUE LEDGERS</span>')}<section class="metric-grid">${metric('OPPORTUNITIES', economy.opportunities_total ?? 0, 'gold')}${metric('GROSS REVENUE', money(economy.gross_revenue_aud))}${metric('NET CASH', money(economy.net_cash_aud))}${metric('CUSTOMERS WON', economy.customers_won ?? 0)}</section><section class="panel activity-panel">${head('DISCOVERY', 'Top opportunities', '<span class="panel-meta">EVIDENCE-BACKED</span>')}${economy.top_opportunities?.length ? `<div class="mission-list">${economy.top_opportunities.map(item => `<div class="mission-card"><div class="mission-card-main"><span class="mission-symbol">◌</span><div><span class="eyebrow">${esc(item.status)}</span><h3>${esc(item.title)}</h3><span class="mono">${esc(item.evidence_count)} evidence · confidence ${Math.round((item.confidence || 0) * 100)}%</span></div></div><span class="authority-state">${money(item.proposed_price_aud)}</span></div>`).join('')}</div>` : empty('No economic opportunities', 'No persisted revenue ledger currently contains an opportunity.')}</section></div>`; }
function render() { const [kicker, title] = views[state.view]; $('#view-kicker').textContent = kicker; $('#view-title').textContent = title; const pages = { overview, agents: agentsPage, missions: missionsPage, evidence: evidencePage, governance: governancePage, operations: operationsPage, economy: economyPage, institutions: institutionsPage, academy: academyPage, world: () => unavailable('World map', 'The runtime exposes an abstract settlement projection, not geographic coordinates.'), entertainment: () => unavailable('Entertainment', 'Entertainment systems are not included in the current console projection.') }; $('#app').innerHTML = pages[state.view](); bind(); }
function unavailable(title, copy) { return `<div class="page-view">${head('CIVILIZATION / SECTOR', title, '<span class="panel-meta">PROJECTION ONLY</span>')}<div class="coming-soon"><span class="coming-orbit">◌</span><span class="eyebrow">SECTOR NOT YET PROJECTED</span><h3>${title}</h3><p>${copy}</p><span class="badge muted">COMING ONLINE</span></div></div>`; }
function closeDrawer() { $('#drawer').classList.remove('open'); $('#drawer').setAttribute('aria-hidden', 'true'); }
function openDrawer(content) { $('#drawer-content').innerHTML = content; $('#drawer').classList.add('open'); $('#drawer').setAttribute('aria-hidden', 'false'); }
async function openRun(id) { try { const run = await api(`/api/runs/${encodeURIComponent(id)}`); openDrawer(`<span class="eyebrow accent">MISSION RECEIPT</span><h2>${esc(run.objective || 'Untitled mission')}</h2><div class="drawer-status">${badge(run.status)} <span class="mono">${short(run.run_id)}</span></div><div class="drawer-section"><span class="eyebrow">RECEIPT</span><div class="receipt-block ${run.receipt?.sealed ? 'sealed' : ''}"><strong>${run.receipt?.sealed ? 'SEALED RECEIPT' : 'RECEIPT NOT SEALED'}</strong><span class="mono">${esc(run.receipt?.hash || 'No receipt hash available')}</span></div></div><div class="drawer-section"><span class="eyebrow">EVENTS</span>${(run.events || []).slice(-12).reverse().map(event => `<div class="drawer-event"><span>${esc(event.agent_id || 'SYSTEM')}</span><strong>${esc(event.summary || event.type || 'Recorded event')}</strong><small>${stamp(event.timestamp)}</small></div>`).join('') || '<p class="muted-copy">No events persisted for this run.</p>'}</div>`); } catch (error) { openDrawer(`<span class="eyebrow">SYSTEM DATA UNAVAILABLE</span><h2>Could not open mission</h2><p>${esc(error.message)}</p>`); } }
function openAgent(id) { const agent = agents().find(item => item.id === id); if (!agent) return; openDrawer(`<span class="eyebrow accent">AGENT DETAIL</span><div class="drawer-agent-sigil">${agent.id === 'SINK-PRIME' ? '◉' : '◈'}</div><h2>${esc(agent.name || agent.id)}</h2><span class="mono">${esc(agent.id)}</span><div class="drawer-status">${badge(agent.enabled ? 'ONLINE' : 'DISABLED')}</div><div class="drawer-section"><span class="eyebrow">AUTHORITY BOUNDARY</span><h3>${authority(agent)}</h3><p>${esc(agent.purpose || 'Bounded runtime identity.')}</p></div><div class="drawer-section"><span class="eyebrow">CAPABILITIES</span><div class="tag-list">${(agent.capabilities || []).map(item => `<span class="tag">${esc(item)}</span>`).join('') || '<span class="muted-copy">No capabilities declared.</span>'}</div></div><div class="drawer-section"><span class="eyebrow">DENIED TOOLS</span><div class="tag-list">${(agent.denied_tools || []).map(item => `<span class="tag danger">${esc(item)}</span>`).join('') || '<span class="muted-copy">No denied tools declared.</span>'}</div></div>`); }
const baseOpenAgent = openAgent;
openAgent = id => { baseOpenAgent(id); const agent = agents().find(item => item.id === id); if (!agent) return; const missions = (state.projection?.missions || []).filter(item => item.responsible?.includes(id) || item.responsible?.includes(agent.name)); const relatedRuns = runs().filter(run => run.tasks?.some(task => task.assigned_agent === id) || run.events?.some(event => event.agent_id === id)); $('#drawer-content')?.insertAdjacentHTML('beforeend', `<div class="drawer-section"><span class="eyebrow">CONNECTED WORK</span>${missions.length ? missions.slice(0, 5).map(item => `<button class="drawer-link" data-navigate="missions"><span><strong>${esc(item.title)}</strong><small>${esc(item.kind)} · ${esc(item.status)} · ${item.evidence_count} evidence</small></span><b>→</b></button>`).join('') : '<p class="muted-copy">No projected missions are assigned to this agent.</p>'}${relatedRuns.length ? `<span class="eyebrow drawer-subhead">RELATED RUNS</span>${relatedRuns.slice(0, 5).map(run => `<button class="drawer-link" data-run-id="${esc(run.run_id)}"><span><strong>${esc(run.objective || 'Untitled run')}</strong><small>${esc(run.status)} · ${short(run.run_id)}</small></span><b>→</b></button>`).join('')}` : ''}</div>`); bind(); };
function bind() { document.querySelectorAll('[data-navigate]').forEach(item => item.addEventListener('click', () => navigate(item.dataset.navigate))); document.querySelectorAll('[data-agent-id]').forEach(item => item.addEventListener('click', () => openAgent(item.dataset.agentId))); document.querySelectorAll('[data-run-id]').forEach(item => item.addEventListener('click', () => openRun(item.dataset.runId))); document.querySelectorAll('[data-filter]').forEach(item => item.addEventListener('click', () => { state.filter = item.dataset.filter; render(); })); document.querySelectorAll('[data-run-cycle]').forEach(item => item.addEventListener('click', runCycle)); $('#prime-command-form')?.addEventListener('submit', executePrimeCommand); }
function navigate(view) { if (!views[view]) return; state.view = view; document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === view)); render(); closeNav(); }
function closeNav() { $('#sidebar').classList.remove('open'); $('#scrim').classList.remove('open'); } function openNav() { $('#sidebar').classList.add('open'); $('#scrim').classList.add('open'); }
function closePalette() { $('#command-palette').close(); } function openPalette() { $('#command-palette').showModal(); $('#command-input').value = ''; renderCommands(''); $('#command-input').focus(); }
function renderCommands(query) { const term = query.toLowerCase(); const viewResults = Object.entries(views).filter(([key, value]) => `${key} ${value[1]}`.toLowerCase().includes(term)); const agentResults = agents().filter(agent => `${agent.id} ${agent.name}`.toLowerCase().includes(term)); $('#command-results').innerHTML = `${viewResults.map(([key, value]) => `<button class="command-result" data-command-view="${key}"><span>◈</span><span>${value[1]}<small>${value[0]}</small></span><kbd>↵</kbd></button>`).join('')}${agentResults.map(agent => `<button class="command-result" data-command-agent="${esc(agent.id)}"><span>◉</span><span>${esc(agent.name || agent.id)}<small>AGENT · ${esc(agent.id)}</small></span><kbd>↵</kbd></button>`).join('')}` || '<div class="palette-empty">No matching records.</div>'; document.querySelectorAll('[data-command-view]').forEach(item => item.addEventListener('click', () => { navigate(item.dataset.commandView); closePalette(); })); document.querySelectorAll('[data-command-agent]').forEach(item => item.addEventListener('click', () => { openAgent(item.dataset.commandAgent); closePalette(); })); }
function attentionBlock() { const items = runs().filter(run => ['FAILED', 'BLOCKED', 'REJECTED'].includes(run.status) || run.errors?.length || (run.receipt && !run.receipt.sealed)); return `<section class="panel attention-panel"><div class="attention-heading"><div><span class="eyebrow">WHAT NEEDS MY ATTENTION</span><h2>${items.length ? `${items.length} item${items.length === 1 ? '' : 's'} require review` : 'All systems clear'}</h2></div><span class="panel-meta">PERSISTED CONDITIONS</span></div>${items.length ? items.slice(0, 6).map(run => `<button class="attention-item" data-run-id="${esc(run.run_id)}"><span class="attention-mark">!</span><span><strong>${esc(run.objective || 'Untitled run')}</strong><small>${esc(run.status)}${run.errors?.length ? ` · ${run.errors.length} errors` : ''}</small></span><span>↗</span></button>`).join('') : '<p class="muted-copy">No failed, blocked, rejected, or unsealed run records are currently reported.</p>'}</section>`; }
function cycleBlock() { const cycle = state.cycles[0]; if (!cycle) return `<section class="panel cycle-panel"><div class="attention-heading"><div><span class="eyebrow">AUTONOMOUS ENGINE / CIVILIZATION LOOP</span><h2>No autonomous cycle has been executed.</h2></div><button class="primary-button" data-run-cycle="dry">Run dry observation</button></div><p class="muted-copy">The engine can observe, analyze, and propose without acquiring execution authority.</p></section>`; return `<section class="panel cycle-panel"><div class="attention-heading"><div><span class="eyebrow">AUTONOMOUS ENGINE / CIVILIZATION LOOP</span><h2>Cycle ${esc(cycle.cycle_id.slice(0, 8))} · ${esc(cycle.status)}</h2></div><button class="primary-button" data-run-cycle="dry">Run another dry cycle</button></div><div class="cycle-grid"><div><span class="eyebrow">OBSERVATION</span><strong>${cycle.observation.settlement.population} people · generation ${cycle.observation.settlement.generation}</strong></div><div><span class="eyebrow">FINDINGS</span><strong>${cycle.findings.length} structured finding${cycle.findings.length === 1 ? '' : 's'}</strong></div><div><span class="eyebrow">PROPOSALS</span><strong>${cycle.proposals.length} mission proposal${cycle.proposals.length === 1 ? '' : 's'}</strong></div><div><span class="eyebrow">AUTHORIZATION</span><strong>${cycle.authorization_decisions.map(item => item.status).join(', ') || 'NONE'}</strong></div></div><p class="muted-copy">No execution is implied by observation or proposal. Evidence and verification remain separate stages.</p></section>`; }
function primeCommandBlock() { return `<section class="panel prime-command-panel"><div><span class="eyebrow accent">PRIME / COMMAND BRIDGE</span><h2>Tell Prime what you want Lake Yange to do.</h2><p class="muted-copy">Prime maps natural language to supported bounded operations. Unsupported work is refused honestly.</p></div><form id="prime-command-form" class="prime-command-form"><input id="prime-command-input" name="command" type="text" placeholder="e.g. Prime, run the next Academy cycle" autocomplete="off" /><button class="primary-button" type="submit">Execute</button></form><div id="prime-command-result" class="prime-command-result" aria-live="polite"></div></section>`; }
async function executePrimeCommand(event) { event.preventDefault(); const input = $('#prime-command-input'); const result = $('#prime-command-result'); const button = $('#prime-command-form button'); if (!input?.value.trim()) return; button.disabled = true; result.textContent = 'Prime is checking the bounded runtime...'; try { const response = await api('/api/prime/agent-command', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ command: input.value }) }); result.innerHTML = `<strong>${esc(response.status)}</strong><span>${esc(response.reply)}</span>`; if (response.status === 'COMPLETED') await refresh(); } catch (error) { result.textContent = error.message; } finally { button.disabled = false; } }
async function runCycle() { const button = document.querySelector('[data-run-cycle]'); if (button) button.disabled = true; try { await api('/api/lake-yange/autonomous/cycle', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ dry_run: true }) }); await refresh(); } catch (error) { if (button) button.textContent = error.message; } }
async function refresh() { try { const [projection, runList, economy, academy, cycles] = await Promise.all([api('/api/lake-yange/world'), api('/api/runs'), api('/api/lake-yange/economy'), api('/api/lake-yange/academy'), api('/api/lake-yange/autonomous/cycles')]); state.projection = projection; state.runs = runList || []; state.economy = economy; state.academy = academy; state.cycles = cycles || []; $('#footer-status').textContent = 'WORLD ONLINE'; $('#sidebar-runtime').textContent = 'CONNECTED'; $('#footer-agents').textContent = agents().length; $('#footer-sync').textContent = clock(new Date()); render(); if (state.view === 'overview') { $('.page-view .content-grid')?.insertAdjacentHTML('beforebegin', primeCommandBlock()); $('.page-view .content-grid')?.insertAdjacentHTML('beforebegin', cycleBlock()); $('.page-view .content-grid')?.insertAdjacentHTML('beforebegin', attentionBlock()); bind(); } } catch (error) { $('#footer-status').textContent = 'PROJECTION UNAVAILABLE'; $('#sidebar-runtime').textContent = 'OFFLINE'; $('#app').innerHTML = `<div class="page-view"><div class="error-state"><span class="empty-glyph">!</span><span class="eyebrow">SYSTEM DATA UNAVAILABLE</span><h2>Lake Yange could not load its projection.</h2><p>The persisted world state is not reachable from this console.</p><button class="primary-button" id="retry-button" type="button">Retry connection</button><details><summary>Technical details</summary><code>${esc(error.message)}</code></details></div></div>`; $('#retry-button')?.addEventListener('click', refresh); } }
document.querySelectorAll('.nav-item').forEach(item => item.addEventListener('click', () => navigate(item.dataset.view))); $('#open-nav').addEventListener('click', openNav); $('#close-nav').addEventListener('click', closeNav); $('#scrim').addEventListener('click', closeNav); $('#close-drawer').addEventListener('click', closeDrawer); $('#refresh-button').addEventListener('click', refresh); $('#command-trigger').addEventListener('click', openPalette); $('#close-palette').addEventListener('click', closePalette); $('#command-input').addEventListener('input', event => renderCommands(event.target.value)); document.addEventListener('keydown', event => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); openPalette(); } if (event.key === 'Escape') { closeDrawer(); closeNav(); if ($('#command-palette').open) closePalette(); } }); await refresh(); setInterval(refresh, 15000);
